2 levels deep.
error: basically, on level 2, it now searches for the "optimal move the opponent can do to improve active player".

on history: N, N
proposal for next move is N :  [N, 1d] and [N,1e]

todo: --> for level 2: check which move from opponent causes maximal damage.